name: Run Tests and Upload Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group tests

      - name: Run tests while collecting coverage data
        run: uv run coverage run --data-file=.coverage/cov -m pytest --durations=3 --junit-xml=.pytest/junit.xml

      - name: Upload unit test results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: .pytest/**/*.xml

      - name: Combine coverage data into a report
        run: |
          uv run coverage combine .coverage/cov*
          uv run coverage report > .coverage/report.md

      - name: Comment the coverage report on the PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: .coverage/report.md
        if: github.event_name == 'pull_request'
